### ISSUE TITLE
Caffe Implementation

### ISSUE THREAD

**Issue by shoaibahmed** [e-lab/ENet-training#13]
Is there any Caffe Implementation for ENet?

**Comment by culurciello** [comment]
http://scienceblogs.com/worldsfair/2009/05/01/lethal-doses-and-substance-abu/
too much Caffe can kill you
;-)

**Comment by culurciello** [comment]
http://scienceblogs.com/worldsfair/2009/05/01/lethal-doses-and-substance-abu/

**Comment by codeAC29** [comment]
No, there is no Caffe implementation of ENet.

**Comment by shoaibahmed** [comment]
Ok, thanks

**Comment by TimoSaemann** [comment]
You may find this [ENet](https://github.com/TimoSaemann/ENet) repository helpful.
