### ISSUE TITLE
CPU Implementation

### ISSUE THREAD

**Issue by ghost** [e-lab/ENet-training#14]
Hi, I would like to use this for segmenting images on CPU. I tried to run the trained classifier to segment one of the image, by taking out the Cuda line in demo.lua. But the model shows requirement for cuda. Is there some option to run it?

Thanks

**Comment by codeAC29** [comment]
@sethitanmay the model provided was trained using cuda. So, you will have to convert `cudnn` modules into `nn` modules in order to be able to use them in CPU.
This can be done by:

```
model = torch.load('trained/model/path/model.net')
cudnn.convert(model, nn)
```
