### ISSUE TITLE
Layers with and without bias

### ISSUE THREAD

**Issue by lvauchier** [e-lab/ENet-training#16]
Hi! 
I read in your paper that you did not use bias terms in your convolution layers, so I wonder why, in your encoder.lua, you use both spatial convolutions with bias and spatial convolutions without bias, for example (line 43-44):
`main:add(cudnn.SpatialConvolution(internal, internal, asymetric, 1, 1, 1, pad, 0):noBias())
 main:add(cudnn.SpatialConvolution(internal, internal, 1, asymetric, 1, 1, 0, pad))`
Thanks for your answer

**Comment by codeAC29** [comment]
@lvauchier We found that getting rid of `bias` from `some` of the layers (not all) gave us early and better convergence.

**Comment by lvauchier** [comment]
Thanks for your quick answer, I think I misunderstood when you wrote 

> We did not use bias terms in any of the projections

I thought it was for every convolutions and not only the 1x1 ones
