### ISSUE TITLE
Problem when training decoder

### ISSUE THREAD

**Issue by ramonss** [e-lab/ENet-training#18]
I'm trying to train the CitySpace dataset using ENet by following the example command in https://github.com/forwchen/ENet-training/tree/master/train. The training of the encoder part seems to have worked with following command:

th run.lua --dataset cs --datapath data/Cityscapes --model models/encoder.lua --save trained_models/tests --imHeight 256 --imWidth 512 --labelHeight 32 --labelWidth 64 --learningRate 5e-4 --weightDecay 2e-4 --batchSize 10

However, when I choose a pre-trained model to train the decoder part I get the following error:

th run.lua --dataset cs --datapath data/Cityscapes --model models/decoder.lua --CNNEncoder trained_models/tests/model-281.net --imHeight 256 --imWidth 512 --labelHeight 256 --labelWidth 512 --learningRate 5e-4 --weightDecay 2e-4 --batchSize 10

==> defining some tools 
==> flattening model parameters 
==> defining training procedure 
Class 'Unlabeled' is ignored in confusion matrix
==> allocating minibatch memory 
==> defining test procedure
==> Training: epoch # 1 [batchSize = 10]
/root/torch/install/bin/luajit: bad argument #2 to '?' (sizes do not match at /root/torch/extra/cutorch/lib/THC/generic/THCTensorCopy.c:64)
stack traceback:
        [C]: at 0x7f818f6cc0d0
        [C]: in function '__newindex'
        ./train.lua:87: in function 'train'
        run.lua:59: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

Could someone let me know if I'm doing something wrong?

Thanks

**Comment by codeAC29** [comment]
Please go through issue https://github.com/e-lab/ENet-training/issues/2

**Comment by ramonss** [comment]
Thank you. Going through issue #2 worked for me as well.
