### ISSUE TITLE
Training with other datasets with different image size

### ISSUE THREAD

**Issue by ramonss** [e-lab/ENet-training#19]
Hello,

I'm trying to train ENet with a different dataset where images and labels have size 500 (width) x 210 (height). I developed my own loadDataset.lua file and added this option in run.lua. However, I'm getting the following error when the data is being loaded:

==> Training: epoch # 1 [batchSize = 10]  
/root/torch/install/bin/luajit: ...all/share/lua/5.1/cudnn/SpatialCrossEntropyCriterion.lua:41: input and target should be of same size
stack traceback:
    [C]: in function 'assert'
    ...all/share/lua/5.1/cudnn/SpatialCrossEntropyCriterion.lua:41: in function 'forward'
    ./train.lua:99: in function 'opfunc'
    /root/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'adam'
    ./train.lua:112: in function 'train'
    run.lua:61: in main chunk
    [C]: in function 'dofile'
    /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670

I would like to load and use the dataset images with their original sizes (no resizing). What should I put as image/label width and height for training the encoder in this case? In my case, I tried the following values assuming that labels in the encoder are normally 1/8th of the original image size in other datasets (e.g., CityScapes):

--imHeight 210 --imWidth 500 --labelHeight 27 --labelWidth 63

Could anyone give some advise?

Thank you.

**Comment by codeAC29** [comment]
Yes, your size of labels should be 1/8th of the original image in case of encoder. In your case image resolution is `210x500` so instead of just diving them by 8, try to put the following before this [line](https://github.com/e-lab/ENet-training/blob/master/train/train.lua#L99) and use the output as your label size.

```
print(y:size())
```

**Comment by ramonss** [comment]
@codeAC29 Thanks for the reply. I tried your suggestion and now I get the following error after using the print(y:size()) output before the line your suggested (--labelHeight 26 --labelWidth 62):

==> defining some tools 
==> flattening model parameters 
==> defining training procedure 
==> allocating minibatch memory 
==> defining test procedure 
==> Training: epoch # 1 [batchSize = 10]  
/root/torch/install/bin/luajit: bad argument #2 to '?' (sizes do not match at /root/torch/extra/cutorch/lib/THC/generic/THCTensorCopy.c:64)
stack traceback:
    [C]: at 0x7f582929a0d0
    [C]: in function '__newindex'
    ./train.lua:87: in function 'train'
    run.lua:63: in main chunk
    [C]: in function 'dofile'
    /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670

Would you have any other suggestion?

Thank you in advance.

**Comment by codeAC29** [comment]
I think you added something else also because your error is now in line 87. This means either `trainData.labels` or `yt` or `shuffle` has different size. Check their sizes in the same way you checked for `y`.

**Comment by ramonss** [comment]
I found the error. The problem was that I did not clean the cache properly and the label dimensions between cache and given parameters were not matching.

Thanks for the help.

**Comment by ramonss** [comment]
@codeAC29 Although training the encoder part was solved, now I have the following similar error when trying to train the decoder part (I made sure the dataset cache has been cleaned before this time):

/root/torch/install/share/lua/5.1/nn/CAddTable.lua:16: bad argument #2 to 'add' (sizes do not match at /tmp/luarocks_cutorch-scm-1-65/cutorch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:198)
stack traceback:
        [C]: in function 'add'
        /root/torch/install/share/lua/5.1/nn/CAddTable.lua:16: in function </root/torch/install/share/lua/5.1/nn/CAddTable.lua:9>
        [C]: in function 'xpcall'
        /root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </root/torch/install/share/lua/5.1/nn/Sequential.lua:41>
        [C]: in function 'xpcall'
        /root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'closure'
        ...t/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:656: in function 'exec'
        ...t/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:195: in function 'forward'
        ./train.lua:100: in function 'opfunc'
        /root/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'adam'
        ./train.lua:119: in function 'train'
        run.lua:63: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
        [C]: in function 'error'
        /root/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
        /root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'closure'
        ...t/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:656: in function 'exec'
        ...t/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:195: in function 'forward'
        ./train.lua:100: in function 'opfunc'
        /root/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'adam'
        ./train.lua:119: in function 'train'
        run.lua:63: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

I'm using the following command to train the decoder part:

th run.lua --dataset myds --datapath data/mydata --model models/decoder.lua --save trained_models/decoder/ --CNNEncoder trained_models/encoder/model-best.net --imHeight 210 --imWidth 500 --labelHeight 210 --labelWidth 500 --learningRate 5e-4 --weightDecay 2e-4 --batchSize 10 --cachepath dataset_cache/decoder/ --nGPU 4 --maxepoch 300

I'm assuming the same sizes for images and labels (Width 500 Height 210) in the decoder training like it is done for other datasets. The label dimensions that worked for the encoder training were labelHeight 26 --labelWidth 62.

Could you give any suggestion on how to solve this error?

Thank you in advance.

**Comment by codeAC29** [comment]
Can you please share the output you get after putting the print statement as I mentioned in the first comment of mine.

**Comment by ramonss** [comment]
@codeAC29 I tried that but it seems that it doesn't output anything. The error seems to be in the [line](https://github.com/e-lab/ENet-training/blob/master/train/train.lua#L97) before =>  'local y = model:forward(x)'.

Maybe related to [this](https://github.com/DmitryUlyanov/texture_nets/issues/24) problem? It is a limitation of the image dimensions that can be used?

**Comment by codeAC29** [comment]
Have you modified the code because in my case line 100 is [this](https://github.com/e-lab/ENet-training/blob/master/train/train.lua#L100) and the error message posted by you has error in line 100 and not 97.

And yes, you need to think about image dimensions which are compatible with the network but that will give you different error. Resolutions in 'powers' of 2 will work all the time.

**Comment by ramonss** [comment]
@codeAC29 It was just my prints to debug, that is why the line number was different from yours. Here is the same error when using the original code in train.lua:

==> Training: epoch # 1 [batchSize = 10]  
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/nn/Container.lua:67: .]  ETA: 0ms | Step: 0ms  
In 27 module of nn.Sequential:
In 2 module of nn.Sequential:
/root/torch/install/share/lua/5.1/nn/CAddTable.lua:16: bad argument #2 to 'add' (sizes do not match at /tmp/luarocks_cutorch-scm-1-65/cutorch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:198)
stack traceback:
    [C]: in function 'add'
    /root/torch/install/share/lua/5.1/nn/CAddTable.lua:16: in function </root/torch/install/share/lua/5.1/nn/CAddTable.lua:9>
    [C]: in function 'xpcall'
    /root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    /root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </root/torch/install/share/lua/5.1/nn/Sequential.lua:41>
    [C]: in function 'xpcall'
    /root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    /root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'closure'
    ...t/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:656: in function 'exec'
    ...t/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:195: in function 'forward'
    ./train.lua:97: in function 'opfunc'
    /root/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'adam'
    ./train.lua:112: in function 'train'
    run.lua:63: in main chunk
    [C]: in function 'dofile'
    /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
    [C]: in function 'error'
    /root/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
    /root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'closure'
    ...t/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:656: in function 'exec'
    ...t/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:195: in function 'forward'
    ./train.lua:97: in function 'opfunc'
    /root/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'adam'
    ./train.lua:112: in function 'train'
    run.lua:63: in main chunk
    [C]: in function 'dofile'
    /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670

Any idea for solving this issue? Is it related to image dimensions after all?

Thanks in advance.

**Comment by jay98** [comment]
I have the same issue, I can't seems to find the error. I haven't changed anything from the repo. I'm using the camvid data so the default values should be fine right ?

I ran the following command : 

th run.lua --dataset cv --datapath /home/jayp/Downloads/ENet-training/train/data/CamVid --model models/decoder.lua --save /home/jayp/Downloads/ENet-training/train/save/trained/model/decoder --cachepath /home/jayp/Downloads/ENet-training/train/data/CamVid/camVid --devid 1 --nGPU 1 --batchSize 10 --CNNEncoder  /home/jayp/Downloads/ENet-training/train/save/trained/model/model-best.net
