### ISSUE TITLE
demo.lua:221: attempt to call method 'squeeze' (a nil value)

### ISSUE THREAD

**Issue by uschmelmer** [e-lab/ENet-training#23]
Hi,
when i am running my self trained model i get the following error for every processed frame and the output windows stays white:

```
demo.lua:221: attempt to call method 'squeeze' (a nil value)
stack traceback:
    demo.lua:221: in function <demo.lua:186>
```

When i run your provided model everything works.
When i run my self trained encoder alone, it is also working (but with reduced output resolution of course).

This is how i proceed:

First i train the encoder:
`th run.lua --dataset cs --datapath /home/udo/CityScapes --model models/encoder.lua --save save/trained/model/ --imHeight 256 --imWidth 512 --labelHeight 32 --labelWidth 64 --nGPU 1`

Than, after moving the database data.t7 to data_enc.t7 (so a new one is created for the decoder with it's correct output resolutin), i train the decoder:
`th run.lua --dataset cs --datapath /home/udo/CityScapes --model models/decoder.lua --save save/trained/model-dec/ --imHeight 256 --imWidth 512 --labelHeight 256 --labelWidth 512 --nGPU 1 --CNNEncoder /home/udo/enet/ENet-training/train/save/trained/model/model-best.net`
Both are running fine and converge as i should.

This is how i run the demo:
`qlua demo.lua -i ~/CityScapes/leftImg8bit/test -d ~/enet/ENet-training/train/save/trained/model-dec/`

I am pointing the demo directly to the saved model of the decoder training, is there some preprocessing step necessary?
The trained decoder model is a bit smaller than the encoder (2983638 vs 2916948). Your model is bigger: 3230016. To the encoder and decoder have to be "fused" in an intermediate step?

Best regards,
Udo

**Comment by p-andra** [comment]
I had the same issue and it seemed that the decoder network was not correctly written to the file. So I made the following changes when training the decoder:

In `test.lua` where the model is saved I changed :
`torch.save(filename, model:clearState():get(1))`
into 
`model:clearState()`
 `torch.save(filename, model)`

Then I made sure that the model was correctly loaded into `demo.lua` and it was for me. Now, the decoder model's size is 3.224.409 bytes, if that helps.

**Comment by codeAC29** [comment]
Thanx @AndraPetrovai !!! The [line](https://github.com/e-lab/ENet-training/blob/master/train/test.lua#L148) which you have mentioned gets rid of `DataParallelTable`. On the other hand, this [line](https://github.com/e-lab/ENet-training/blob/master/visualize/demo.lua#L42) in `demo.lua` enables user to get rid of `DataParallelTable` in case the network was trained using some other training script.
This should not have created any problem but thanks for pointing it out. I will look into it.

In the meantime @uschmelmer please let us know if the solution provided above worked for you.

**Comment by uschmelmer** [comment]
Hi, thank your very much for the hint!
I will test the Code tomorrow morning and report back as soon as possible!
Best Regards,
Udo

**Comment by uschmelmer** [comment]
Hey,
Andras patch works for me! Thank you very much!
Best Regards,
Udo

**Comment by codeAC29** [comment]
Thank you @uschmelmer for confirming. Can you plz tell what do you get when you load your trained decoder and try to print `network.model.__typename`?

**Comment by uschmelmer** [comment]
Hi @codeAC29 ,
the now working model is of type: nn.DataParallelTable

**Comment by Mina1368** [comment]
Hi, 
I got this error:
lapp.lua:321: attempt to get length of local 'arg' (a nil value)

any suggestions guys?

Best,
Mina

**Comment by deepcode123** [comment]
It also works for me.
Thanks!!

**Comment by codeAC29** [comment]
Thanks @uschmelmer
