### ISSUE TITLE
How to interpret unlabeled areas?

### ISSUE THREAD

**Issue by Timo-hab** [e-lab/ENet-training#27]
The visualization of the predictions of ENet contains some unlabeled areas. Does that areas mean, that the net is not sure about the right class or is it trained as an own class? Is it possible to turn off this areas, so the network have to classify every pixel to the remained classes. Or is there a threshold? Thank you in advance!

**Comment by codeAC29** [comment]
The unlabeled class is part of the class list provided by the dataset. Classes which are not of interest can be put in `unlabeled` classes by using the [mapping table](https://github.com/e-lab/ENet-training/blob/master/train/data/loadCityscape.lua#L33).
We force the network to not learn this class through [this](https://github.com/e-lab/ENet-training/blob/master/train/models/decoder.lua#L123) line.

**Comment by ethanyanjiali** [comment]
i'm still quite confused here, if you set weight to 0 for unlabeled area, how do you punish the network when it falsely predict a background pixel as a road pixel? since weight is 0 there won't any loss for this pixel.
