### ISSUE TITLE
is there a plan for  c++ version of Enet? 

### ISSUE THREAD

**Issue by bsaint** [e-lab/ENet-training#30]
I currently noticed this network and want to try it. Because i am not familiar with torch, i wonder whether there will be or have existed any work to implement enet with caffe? I have tried the fb-torch2caffe converter, but it is out-of-date and cant support enet.

**Comment by codeAC29** [comment]
Look into #13

**Comment by TimoSaemann** [comment]
You may find this [ENet](https://github.com/TimoSaemann/ENet) repository helpful.
