### ISSUE TITLE
Where to set #classes

### ISSUE THREAD

**Issue by Mina1368** [e-lab/ENet-training#31]
Hi, 
I have a same dataset as CamVid except with two classes, I assume the only where that needs to modify is loadCamvid.lua. I changed the classes and conClasses. Also I changed this line mask = rawImg:eq(13):float() to mask = rawImg:eq(3):float().

I could train the encoder part, but for the decoder the result has 13 classes.

Is there anywhere I should change?

-Best
Mina

**Comment by codeAC29** [comment]
You need to make changes only in `loadCamvid.lua`. What is the value of `#classes` after [this](https://github.com/e-lab/ENet-training/blob/master/train/models/decoder.lua#L17) line?

**Comment by Mina1368** [comment]
It seems that no matter which dataset I use, the decoder part is as follow, which is only one layer of convolution with 13 filters. Do you have any idea where to fix?

th> model = torch.load('model-4.net')
th> model
nn.ConcatTable {
  input
    |`-> (1): cudnn.SpatialConvolution(3 -> 13, 3x3, 2,2, 1,1)
`-> (2): nn.SpatialMaxPooling(2x2, 2,2)
     ... -> output
}

**Comment by Mina1368** [comment]
Yes, the #classes is fine.

**Comment by ishann** [comment]
As a sanity check consider looking at the models you're loading, and if they are pointing to the correct directories.

Since the dimensions are not hard-coded in the model/train/test files, this might be due to the pre-loaded model you're using.

**Comment by ishann** [comment]
On closer inspection, I did find [this](https://github.com/e-lab/ENet-training/blob/master/train/models/encoder.lua#L80) in the encoder file pointing to a hard-coded dimension. This might fix your problem.

**Comment by codeAC29** [comment]
See if you have the same issue as #3

**Comment by Mina1368** [comment]
Thank you ishann and codeAC29, you were right, I was looking at wrong model. It works perfectly now!
