### ISSUE TITLE
No result to visualize

### ISSUE THREAD

**Issue by ghost** [e-lab/ENet-training#35]
I was trying to train the encoder and decoder and then visualize that for CityScape. Training for encoder is:
th run.lua --dataset cs --datapath ~/Desktop/Dataset/CityScape --model models/encoder.lua --save data/CityScape/trained_encoder/ --imHeight 256 --imWidth 512 --labelHeight 32 --labelWidth 64 --cachepath data/CityScape/enc_cache/ --nGPU 1  --lrDecayEvery 10 -b 5 --maxepoch 100
Training for decoder is:
th run.lua --dataset cs --datapath ~/Desktop/Dataset/CityScape --model models/decoder.lua --imHeight 256 --imWidth 512 --labelHeight 256 --labelWidth 512 --CNNEncoder data/CityScape/trained_encoder/model-best.net --nGPU 1 --cachepath data/CityScape/dec_cache/ --save data/CityScape/trained_decoder/ --lrDecayEvery 10 -b 5 --maxepoch 100

I used the best decoder model to visualize, however the e-Lab Scene Parser is just a white window with classes listed on the side. The error is:
video statistics: 29.979879275654 fps, 360x640 (149 frames)
Press Spacebar to pause or
      Right Arrow to skip forward or
      Esc to exit
demo.lua:221: attempt to call method 'squeeze' (a nil value)
stack traceback:
	demo.lua:221: in function <demo.lua:186>
demo.lua:221: attempt to call method 'squeeze' (a nil value)
stack traceback:
	demo.lua:221: in function <demo.lua:186>
demo.lua:221: attempt to call method 'squeeze' (a nil value)
stack traceback:
	demo.lua:221: in function <demo.lua:186>
demo.lua:221: attempt to call method 'squeeze' (a nil value)

What's the possible problem here?

**Comment by codeAC29** [comment]
Issue #23
