### ISSUE TITLE
Class Accuracy is 0

### ISSUE THREAD

**Issue by ghost** [e-lab/ENet-training#36]
I'm training both encoder and decoder on the CamVid dataset and use `--noConfusion all`. It works fine for encoder, while for decoder, the class accuracies for column-pole, sign-symbol, pedestrian and bicyclist are 0.000% during both training and testing. I'm not sure why this could happen? The dataset was downloaded from SegNet github, and the image size is kept as it is (360x480).
Here's confusionMatrix for one model:
Testing:
```
================================================================================
ConfusionMatrix:
[[ 6378220   69799      10      23     124  301373       0    3156   11950       0       0]   94.287% 	[class: Sky]
 [  137783 8384576       4   12455   44300  470470       0  397151  318598       3       0]   85.861% 	[class: Building]
 [   44235  287893       2     255    3949   56334       0   36627   41310       0       0]   0.000% 	[class: Column-Pole]
 [      10   20881       0 9232678  701740      26       0   28850  281855       0       0]   89.934% 	[class: Road]
 [       2   42951       0  656156 2133744       7       0   41084  820141       0       0]   57.761% 	[class: Sidewalk]
 [  281655 1948040       3     127    1128 2107336       0  118706   53577       3       0]   46.720% 	[class: Tree]
 [    7756  339229       0       6     132   44766       0    6926    2599       0       0]   0.000% 	[class: Sign-Symbol]
 [     910  262004       1    2599    6494    4922       0  108354   81889       0       0]   23.194% 	[class: Fence]
 [    5352  131591       1   64122   61088   11641       0   68830 1224900       0       0]   78.142% 	[class: Car]
 [      47  165030       0     303     944      93       0   62262   25160       0       0]   0.000% 	[class: Pedestrian]
 [       3   24571       0    1233    2030     177       0   29364   16965       0       0]]  0.000% 	[class: Bicyclist]
 + average row correct: 43.263584944676% 
 + average rowUcol correct (VOC measure): 33.552783618056% 
 + global correct: 77.335819603064%
```

**Comment by codeAC29** [comment]
These classes have very few samples. Thats why we use class balancing technique; in case of `Cityscapes` we use a value of 1.02 but for `CamVid` try to use 1.04 or 1.2 in this [line](https://github.com/e-lab/ENet-training/blob/master/train/models/decoder.lua#L129).

And sorry about modifying your comment. I did that to make it more readable.

**Comment by ghost** [comment]
I tried 1.2 but they're still 0. Not sure why? I used batch size 5 for encoder, but size 4 for decoder.

**Comment by Nestarneal** [comment]
Hi codeAC29,

Could you tell me how about the value for SUN RGB-D dataset?
Is that value also be 1.02 if I want to re-produce your benchmark result?

Many thanks!

**Comment by ghost** [comment]
I tried c=1.04 for CamVid. 
Changed it not only in decoder.lua but also in encoder.lua, fixed the 0 accuracy problem.

**Comment by ghost** [comment]
@Nestarneal   I would recommend you try different ways to balance the class weight. You'll see the accuracy changes a lot with different methods.

**Comment by codeAC29** [comment]
@wzhouuu thank you for verifying the result and yes, class balancing techniques greatly affect accuracies. Other existing approach use median frequency balancing, which did not give us good result.
