### ISSUE TITLE
Training on SUN RGB-D dataset

### ISSUE THREAD

**Issue by Nestarneal** [e-lab/ENet-training#37]
Hi,

I want to train ENet model on SUN RGB-D dataset, but I found that the ground truth of each image is not consistent.

I following the source code to load the label of each image with
`m = require 'matio'`
`label = m.load(/path/to/folders/'seg.mat').seglabel`
Then, drawing an output image with the label, and making different index label has different color.

But, for example, beds are labelled with different color/index in following images
![0000001](https://cloud.githubusercontent.com/assets/16053646/21036789/6476d8ac-be03-11e6-8e93-933f277ac9ed.jpg)
![0000001_color_gt](https://cloud.githubusercontent.com/assets/16053646/21036793/6ca4d9b6-be03-11e6-9a8c-2e172d803ac1.png)
![0000002](https://cloud.githubusercontent.com/assets/16053646/21036796/70a80bdc-be03-11e6-84ae-a6ec11f47aeb.jpg)
![0000002_color_gt](https://cloud.githubusercontent.com/assets/16053646/21036800/737eef56-be03-11e6-9af2-a5561f2e023f.png)

And other objects have different index in different images.
Also, SUN RGB-D dataset has 38 classes (including unlabelled class), so the index interval should be [0, 37] or [1, 38].
But some seg.mat file has the index number larger than 37 and 38, for example, 45, 46 appeared.

I'm wonder what's going wrong about the ground truths?

Many thanks.

**Comment by Nestarneal** [comment]
Hey, I found the answer.
Closing the issue.

**Comment by xiaofanglegoc** [comment]
@Nestarneal  could you please give  more details on how you produce the results on SUNRGBD ? I try to train the ENet on the SUNRGBD also. But I have encountered  following bugs: 1, some images do not exist in the file sunImgPath.tsv (So I skip those images); 2, values in some images go to 143, while they are supposed in [0 38]. 
Thank you very much

**Comment by Nestarneal** [comment]
@xiaofanglegoc ,
I have no idea about your first problem because I didn't encounter it.
And for the second problem, you can try
`m = require 'matio'`
`m.use_lua_strings = true`
`gt = m.load('/path/to/seg.mat')`
`local_label = gt.seglabel`
`local_table = gt.names`
The indexes in local_label in based on local_table, 
so you need to convert the indexes into global indexes before training.

**Comment by xiaofanglegoc** [comment]
Thank you very much, I have solved my problem

**Comment by rantengsky** [comment]
how to convert the indexes into global indexes?

**Comment by guy4261** [comment]
@Nestarneal 

In the `SUNRGBDtoolbox.zip`, under `Metadata`, there's a file containing all the segmentations. The values are in [0, 37] (aka both are included) - so there is one extra class for "no-class". But is it 0 or 37? Did you find this out?

Thanks!
