### ISSUE TITLE
Reproducing Results

### ISSUE THREAD

**Issue by dylanheld** [e-lab/ENet-training#38]
Hello, I've been able to successfully retrain an encoder and decoder model using the Cityscape dataset and the output from the visualization scripts looks great; however I was wondering how one would go about outputting the IoU mAP results on the 1525 test images (Cityscape) stated in the paper with this model. I'd like to confirm that my model produces similar results to the following:
![image](https://cloud.githubusercontent.com/assets/18606576/21066503/deeb6758-be33-11e6-8544-99325e2e08c6.png)

There doesn't appear to be a dedicated script to do this in the repo.

**Comment by codeAC29** [comment]
We followed the instructions provided in the cityscapes website and submitted our results to get performance values on `validation` data.

**Comment by dylanheld** [comment]
Thank you; I followed a similar process and received comparable results.
