### ISSUE TITLE
Preprocessing Issue - Data Size

### ISSUE THREAD

**Issue by chuanzihe** [e-lab/ENet-training#4]
Hi Adam,
May I know have you resized the input resolution before training?
The original Cityscapes datasets have the resolution of **2048x1024**, however in [README.md](https://github.com/e-lab/ENet-training/tree/master/train) it seems that you use **512x256** as the input size.

I used 

```
 --dataset cs --imHeight 256 --imWidth 512 --labelHeight 32 --labelWidth 64

```

and 

```
 --imHeight 256 --imWidth 512 --labelHeight 256 --labelWidth 512
```

to train an encoder and a decoder with 2048x1024 input. No error was reported however the visualized result was rather rough(using your visualize tool). I wonder if there is any mistake with input data.

![visualized output](https://cloud.githubusercontent.com/assets/19618625/17162453/1f55b4bc-536b-11e6-891f-05dfeef9dc2d.png)

Thanks for your answering!

**Comment by codeAC29** [comment]
Hello @clairematrix

You used -imHeight/imWidth as 256 and 512. It means you downsampled and trained your network at 512x256 resolution and not 2048x1024.

Since you trained it on lower resolution, it will make sense to do same while visualization, i.e. set -r option to 0.5.

**Comment by chuanzihe** [comment]
Hi @codeAC29 

Thanks for the quick response! It works much better. Look like this:

![save_out_refined](https://cloud.githubusercontent.com/assets/19618625/17163037/294d62a8-5370-11e6-89b2-df5239127a09.png)

So will the testing error decrease if I train it with -imHeight/imWidth as 1024 and 2048? How did you preprocess your data? Because I visualized it with model-best.net, which is the result of an encoder training. 

The best testing error of encoder training is 

```
Best test error: 0.4738311638236, in epoch: 60

```

However when I used the model-best.net(encoder training) to train the decoder, it turned out that 

```
Best test error: 0.77272008287907, in epoch: 72
```

FYI, I used 

```
th run.lua --dataset cs --model models/decoder.lua --imHeight 256 --imWidth 512 --labelHeight 256 --labelWidth 512 -b 2

```

when training the decoder.

**Comment by codeAC29** [comment]
We did not try to train on full resolution image (2048x1024) because of memory constraints. Error might improve but it should not vary a lot (in my opinion).
Preprocessing data for visualization? No, we do not preprocess it.
Batchsize used while training also affects the result. See if you get better result with batchsize of 8.

**Comment by chuanzihe** [comment]
So you resized the original full resolution one into 512x256 then go to training? Or simply set the imHeight and imWidth is actually doing the resizing?

Thank you! @codeAC29

**Comment by codeAC29** [comment]
`imWidth` and `imHeight` resizes the image and stores the dataset at `cachepath`.

**Comment by chuanzihe** [comment]
Cool. Thank you.

On Wed, Jul 27, 2016 at 4:16 PM -0700, "Abhishek Chaurasia" <notifications@github.com<mailto:notifications@github.com>> wrote:

imWidth and imHeight resizes the image and stores the dataset at cachepath.

##
