### ISSUE TITLE
Training Enet on a custom dataset

### ISSUE THREAD

**Issue by souravsingh** [e-lab/ENet-training#40]
I am looking to train an Enet infrastructure on the dataset available here- https://github.com/jeanpat/DeepFISH

What are the points that I need to take care about when training the dataset on Enet and steps for training the dataset.

**Comment by codeAC29** [comment]
@souravsingh you will need to add a data loader. Follow the format used in any of the data loader of this repository and call that data loader [here](https://github.com/e-lab/ENet-training/blob/master/train/run.lua#L31).
Just keep in mind that your train/test data and labels follow [this](https://github.com/e-lab/ENet-training/blob/master/train/data/loadCityscape.lua#L154) format. Also, make sure you have all [these](https://github.com/e-lab/ENet-training/blob/master/train/data/loadCityscape.lua#L303) return values.
