### ISSUE TITLE
demo.lua:200 attempt to index local 'img' (a nil value)

### ISSUE THREAD

**Issue by MikepX99** [e-lab/ENet-training#42]
Hi all, I am trying to visualize the results and I am running into some snafoos.  I added fastimage.so to torch/install/lib/lua/5.1 to get around the fastimage.so not found error after I run this command:

`qlua demo.lua -i ../train/data/Cityscapes/leftImg8bit/test/ -d ../save/ -m decoder2 --net 16`

The e-Lab Scene Parser opens but all I see is a white screen except for the colored legend that shows up on the side.  This is the error that I get:

`demo.lua:200: attempt to index local 'img' (a nil value)
stack traceback:
	demo.lua:200: in function <demo.lua:186>`

Any help would be greatly appreciated!

**Comment by MikepX99** [comment]
So what ended up happening was that I needed to specify a specific folder in the test directory.  It was failing at the forward command because it was trying to find the next image in the directory however there were actually no images in the directory I was pointing it at.  So my command became 

`qlua demo.lua -i ../train/data/Cityscapes/leftImg8bit/test/berlin/ -d ../save/ -m decoder2 --net 16`

**Comment by codeAC29** [comment]
Yes, the demo script looks into a folder for images and CANNOT look into folder of folder for images.

**Comment by shanmugaraj1986** [comment]
Hi Guys how did you added the fastimage, I am new to this, I am running demo.lua, but it requires fastimage, please help me to install fast image. Thanks
