### ISSUE TITLE
Bad segmentation quality

### ISSUE THREAD

**Issue by enigmanx** [e-lab/ENet-training#43]
Hi
I download this implementation of ENet, and download trained model, as mentioned in repo, but after processing, I got bad segmentation results. 

Is it trained model and it is no need to train it? Should I train my own model to get good result or I run something wrong?

![screen sharing picture january 18 2017 at 5 01 46 pm gmt 3](https://cloud.githubusercontent.com/assets/5937999/22104795/058ec95c-de52-11e6-9eee-7271ba5804dc.png)

Thx

**Comment by suhinini** [comment]
Oh jeez ur network does no good, huh?

**Comment by codeAC29** [comment]
@enigmanx  yes it is a trained model but it was trained on cityscapes dataset. Cityscapes does not contain indoor images, so you cannot expect it give meaningful segmentation on the image which you provided.
