### ISSUE TITLE
got scripts implemented bu pytorch?

### ISSUE THREAD

**Issue by brb-chen** [e-lab/ENet-training#44]
Hi, adam, i saw you stay in the team of pytorch, did you consider implement ENet in pytorch?

**Comment by culurciello** [comment]
we should have enet for imagenet converted soon:
https://github.com/e-lab/imagenet-multiGPU.torch/blob/master/models/enet.lua
we may do this repo also, but not sure now

**Comment by brb-chen** [comment]
thks,  what's about the expriment result about mscoco? did u validate it ?
