### ISSUE TITLE
Bad argument #1 to 'indexAdd' in confusionMatrix.lua

### ISSUE THREAD

**Issue by ghost** [e-lab/ENet-training#45]
I've successfully trained several models on CamVid and CityScape. But when I try to train on my own dataset, which I labeled it according to CamVid category rules and applied data augmentation to them, something went wrong with confusion matrix. 
When I trained on original labeled data, everything went well. But when I trained on augmented data, it gave me this error. I could reckon this error is occurred because of the augmented label image. But I'm not sure what exactly does this error mean? Btw, without --noConfusion option, the training is working.
![screenshot](https://cloud.githubusercontent.com/assets/24283641/23238914/783a760a-f9b8-11e6-94a8-27037f10efde.png)

**Comment by ghost** [comment]
Well, I think I know what's wrong here. After data augmentation, the label index is actually out of CamVid index range.

**Comment by codeAC29** [comment]
@wzhouuu that is correct, and generally to debug these indices I try to see the value of `x` during remapping process. (for example [this line](https://github.com/e-lab/ENet-training/blob/master/train/data/loadCityscape.lua#L245))

**Comment by ghost** [comment]
Thanks for that!  
Close issue
