### ISSUE TITLE
Save segmented labels

### ISSUE THREAD

**Issue by ghost** [e-lab/ENet-training#46]
Is there anyway to save the label result (saying just class number from 0-11 for 1-N) as an image file? It should be the tensor 'winners' from demo.lua in visualize. I could image.display(winners) but I couldn't image.save(winners) as it would save an image with all pixels at 255.

**Comment by codeAC29** [comment]
@wzhouuu there might be better ways than this but what I use is, say you want to see the results for class/label `i`. You can use the following:
```
label_i = winners:eq(i)
```
This will give you a byte tensor (mask for class `i`). After this you can just save this mask as image file.

**Comment by wzhouuu** [comment]
So this will give me #classes masks (roughly 12 masks for every CamVid image). If I want to have only one image consisting of all class numbers, I know I could do that in Matlab. But is there anyway to do it in Lua? image.save just messed up every index and I couldn't even winners/255 to clamped then to [0,1].

**Comment by wzhouuu** [comment]
So this will give me #classes masks for one image. But is there anyway to save only one index image? I could combine them in Matlab, but not sure if it's possible in Lua straightaway?

**Comment by ghost** [comment]
change the 'winners' type to float and 'winners/255' can be saved as image. solved the problem. Thanks!
