### ISSUE TITLE
Port to keras + license

### ISSUE THREAD

**Issue by PavlosMelissinos** [e-lab/ENet-training#49]
Hello,

I have [ported Enet to the keras framework and recently published it on github (for personal/research use)](https://github.com/PavlosMelissinos/enet-keras). I know I should have asked you beforehand but I was wondering what kind of attribution would be acceptable and whether a MIT license would be ok for distribution (so that I can merge the code with keras-contrib).

Thank you for your work!

**Comment by codeAC29** [comment]
@PavlosMelissinos thanx for the Keras version of ENet. You should use the same license used in ENet repository.

**Comment by PavlosMelissinos** [comment]
Thanks!
