### ISSUE TITLE
Decoder Training Issue

### ISSUE THREAD

**Issue by chuanzihe** [e-lab/ENet-training#5]
Hi, I have some questions about the training process.

Should I train the encoder first then use the model-best.net to train the decoder? I did so. 

The best testing error of encoder training is

`Best test error: 0.4738311638236, in epoch: 60`

However for decoder: 

`Best test error: 0.77272008287907, in epoch: 72`

I trained the decoder for several times, the best test error was approximately the same. So I wonder if I made any mistakes in the training settings.

**Comment by chuanzihe** [comment]
FYI, here's my opt.txt file of the encoder and decoder.

#**Encoder**

```
smallNet : false
learningRate : 0.001
datahistClasses :   810274
 1969251
  321342
 1195839
   34488
   46349
   65294
   10960
   29268
  835925
   61092
  202450
   65301
    7305
  371063
   14192
   12671
   12402
    5239
   22095
[torch.FloatTensor of size 20]

batchSize : 2
dataconClasses : table: 0x419ac960
dataClasses : table: 0x419ac828
channels : 3
printNorm : false
save : savemodel/trained
CNNEncoder : enc/model-100.net
labelHeight : 32
labelWidth : 64
weightDecay : 0.0005
nGPU : 2
lrDecayEvery : 100
model : models/encoder.lua
imHeight : 256
dataset : cs
momentum : 0.9
devid : 1
cachepath : savemodel/media/
datapath : datasets/Cityscapes
threads : 8
maxepoch : 300
noConfusion : skip
learningRateDecay : 1e-07
plot : false
imWidth : 512

```

#**Decoder**

```
smallNet : false
learningRate : 0.001
datahistClasses :   45323724
 127228632
  20988628
  78573240
   2259981
   3025684
   4230457
    716094
   1900118
  54828056
   3993315
  13767863
   4206164
    466290
  24125912
    922413
    811419
    803171
    340114
   1427811
[torch.FloatTensor of size 20]

batchSize : 2
dataconClasses : table: 0x41642c70
dataClasses : table: 0x41642b38
channels : 3
printNorm : false
save : savemodel/
CNNEncoder : savemodel/trained/model-best.net
labelHeight : 256
labelWidth : 512
weightDecay : 0.0005
nGPU : 2
lrDecayEvery : 100
model : models/decoder.lua
imHeight : 256
dataset : cs
momentum : 0.9
devid : 1
cachepath : savemodel725/
datapath : datasets/Cityscapes
threads : 8
maxepoch : 300
noConfusion : skip
learningRateDecay : 1e-07
plot : false
imWidth : 512

```

Thanks for your help!

**Comment by codeAC29** [comment]
Yes you need to train encoder first and only then you can train a decoder.
Error after training decoder is higher than that for the encoder because in case of decoder you need to have fine segmentation for an image of resolution 512x256 but in case of decoder final output resolution is only 64x32.
Btw if you are interested in looking at confusion matrix then I would suggest you to set option
`--noConfusion all`.

**Comment by chuanzihe** [comment]
@codeAC29 
Great! Thank you Abhishek. :)  I will re-train it  later.
