### ISSUE TITLE
Requirement libraries?

### ISSUE THREAD

**Issue by ThomasLengeling** [e-lab/ENet-training#54]
Hi want to test your results and code, do you by chance a small documentation with the required libraries to run your model?, I know that torch7 is required to execute the code. Thank you for the contribution
Thomas

**Comment by codeAC29** [comment]
@ThomasLengeling For training the model, you do not need anything other than standard `Torch` packages. For visualization you do need some other packages which are listed [`here`](https://github.com/e-lab/ENet-training/tree/master/visualize#requirements).
