### ISSUE TITLE
End-to-end training

### ISSUE THREAD

**Issue by ding-s-h** [e-lab/ENet-training#55]
Hi, thank you for sharing the code, I just have a question for the training.
I see that the encoder and the decoder are trained separately, is there any reason that an end-to-end training won't work? Or what result can be expected if we put them into 1 single network and train the whole thing directly? Thanks!

**Comment by codeAC29** [comment]
@DingGit In case of end-to-end training, we will be optimizing a lot of parameters in one go. On the other hand when you train only encoder then you have to optimize fewer parameters. Once these weights are already 'acceptable', training encoder-decoder together becomes much easier.

**Comment by ding-s-h** [comment]
@codeAC29 Thanks for the reply! So just to clarify, when you say the training becomes much easier, do you mean it converges faster or has higher accuracy after converge? Does the end-to-end training eventually converges to the same loss level as the separate training?

**Comment by codeAC29** [comment]
@DingGit we saw it converging faster so we did not bother using end-to-end training. Thats why I cannot comment on the loss value using end-to-end training method. If you train that way and find something interesting then let us know :)
