### ISSUE TITLE
Explanation for the resnet view

### ISSUE THREAD

**Issue by syed-ahmed** [e-lab/ENet-training#6]
Hi,

I am wondering, how do you go about what kind of resnet view is appropriate? For instance: in your paper, you present a resnet view of 3 conv layers with a bunch of prelus and stuff. In the inception-resent-v1, there is a resnet view like:
![screenshot from 2016-08-01 15 14 44](https://cloud.githubusercontent.com/assets/8906225/17305859/c6f74b5c-57fa-11e6-91d6-86ba5019537e.png)
In other words, how do you make this design decision? Does it depend on the type of scene you are training on? 

Second question is how do you make the design decision on the number of bottlenecks? For instance, you have a pattern of dilated, asymmetric, dilated twice in the encoder. Once again, is this number of bottlenecks dependent on the kind of scene like Suncam, cityscape etc or is just that the design decision on how deep the network is arbitrary and the deeper network, the better accuracy?

**Comment by culurciello** [comment]
It is done with a lot of experiments. Heuristics!!!
This may also help you:
http://culurciello.github.io/tech/2016/06/20/training-enet.html

**Comment by syed-ahmed** [comment]
Hi @culurciello, Thank you for your reply. That blog post was helpful. Another part I'm confused at is the concatenation part. One of the differences in the inception v4 model compared to the inception-resnet-v1 paper is the identity shortcut connection as seen in the above picture as opposed to filter concatenation in inception v4. I think ENet uses the torch operation JoinTable to achieve the concatenation. My question is do they essentially do the same thing - filter concatenation vs identity shortcut connection?

**Comment by culurciello** [comment]
yeah it is the same
