### ISSUE TITLE
Do you freeze weights of encoder while training the whole model

### ISSUE THREAD

**Issue by sebastiangonsal** [e-lab/ENet-training#61]
Do you fix the encoder weights while training the whole model with the decoder?  I did not see any code for that in run.lua.

If not, then what is the use of training the encoder separately? Is it for faster convergence when training the entire model?

**Comment by codeAC29** [comment]
Encoder is trained separately and then encoder and decoder are trained together. May be you will find this [line](https://github.com/e-lab/ENet-training/blob/master/train/models/decoder.lua#L25) helpful.
Also #55.
