### ISSUE TITLE
In frameimage.lua:17: module 'fastimage' not found:

### ISSUE THREAD

**Issue by ChidanandKumarKS** [e-lab/ENet-training#64]
Iam getting error In frameimage.lua:17: module 'fastimage' not found:

Kindly suggest to resolve this error

Regards
Kumar

**Comment by gsp-27** [comment]
Download the torch-toolbox, provided [here](https://github.com/e-lab/torch-toolbox), go inside video-decoder folder and make it. This will generate a shared object file named fastimage.so, put this in ~/torch/install/lib/lua/5.1/.
Done, now run the code

**Comment by ChidanandKumarKS** [comment]
I followed the procedure mentioned by u in previous step. I worked... Thanks for your cooperation
