### ISSUE TITLE
Error: torch/File.lua:375: unknown object

### ISSUE THREAD

**Issue by ghost** [e-lab/ENet-training#7]
Hi, when running demo.lua on a video, I get the following error. My model and category file have been downloaded from the dropbox link in the repo readme.md

thx for your help.

```
djeb@DjebPC:~/ENet-training/visualize$ qlua demo.lua -i ~/Desktop/myVideo.mp4
GPU # 1 selected
Loading model from: /home/djeb/ENet-training/visualize/model/model-best.net
qlua: /home/djeb/torch/install/share/lua/5.1/torch/File.lua:375: unknown object
stack traceback:
    [C]: at 0x7f3093f069c0
    [C]: in function 'error'
    /home/djeb/torch/install/share/lua/5.1/torch/File.lua:375: in function 'readObject'
    /home/djeb/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
    demo.lua:63: in main chunk
```

**Comment by codeAC29** [comment]
It is looking for stat file which is not there in the folder. Can you delete line 62 and 63 and see if you are able to run the code.

**Comment by ghost** [comment]
It's crashing at line 61 actually. The network seems not being able to load the stat file accordingly... My stat file is the categories.txt

**Comment by ghost** [comment]
Problem solved. I did not need a stat file at all. Commenting the whole section made it work.
